#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
PROMPT_FILE="$REPO_ROOT/prompts/fix.txt"
MODEL="llama3.1"
OLLAMA_HOST="http://localhost:11434"

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: fix-and-pr.sh <file> \"<issue description>\""
  echo "Example: fix-and-pr.sh src/auth.py \"SQL injection in login function line 42\""
  exit 1
fi

FILE="$1"
ISSUE="$2"
CODE=$(cat "$FILE")

if [ -z "$CODE" ]; then
  echo "Error: could not read $FILE"
  exit 1
fi

PROMPT=$(sed -e "s|{issue}|$ISSUE|g" -e "s|{code}|$CODE|g" "$PROMPT_FILE")

echo "=== Generating fix for: $FILE ==="
echo ""

FIX=$(curl -s "$OLLAMA_HOST/api/generate" \
  -H "Content-Type: application/json" \
  -d "{\"model\": \"$MODEL\", \"prompt\": $(echo "$PROMPT" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))'), \"stream\": false}" \
  | python3 -c "import json,sys; print(json.load(sys.stdin)['response'])")

echo "$FIX"
echo ""

read -p "Apply this fix and open a draft PR? [y/N] " CONFIRM
if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
  echo "Aborted."
  exit 0
fi

BRANCH="llama-fix/$(basename "$FILE" | tr '.' '-')-$(date +%s)"
git checkout -b "$BRANCH"

echo "$FIX" > "$FILE"
git add "$FILE"
git commit -m "fix: Llama-proposed fix for $FILE

Issue: $ISSUE

Auto-generated by code-reviewer — requires human review before merging."

git push origin "$BRANCH"

gh pr create \
  --draft \
  --title "fix: Llama-proposed fix for $(basename "$FILE")" \
  --body "## Issue
$ISSUE

## Proposed Fix
This PR was generated by the local Llama code-reviewer tool.

**This is a draft PR. A human must review, approve, and merge it.**

## Checklist
- [ ] Reviewed the proposed fix
- [ ] Tested locally
- [ ] Approved to merge" \
  --assignee "@me"

echo ""
echo "Draft PR created. Review it on GitHub before merging."
